export const wordList = [
    
  { word: "compass", hint: "It always points north and helps with navigation." },
  { word: "pyramid", hint: "A triangular ancient structure found in Egypt." },
  { word: "cactus", hint: "A spiky plant that survives in the desert." },
  // { word: "lantern", hint: "A portable light source used during camping or power cuts." },
  // { word: "parachute", hint: "Used to safely descend from an aircraft." },
  // { word: "volcano", hint: "A mountain that can erupt with lava." },
  // { word: "monastery", hint: "A place where monks or nuns live." },
  // { word: "harpoon", hint: "A spear-like weapon used for hunting whales or big fish." },
  // { word: "aviation", hint: "The science or practice of flying aircraft." },
  // { word: "quarantine", hint: "Isolation to prevent the spread of disease." },
  // { word: "binoculars", hint: "Used to see distant objects more clearly." },
  // { word: "pirate", hint: "A person who attacks ships at sea." },
  // { word: "saddle", hint: "A seat placed on the back of a horse." },
  // { word: "puzzle", hint: "A game or problem that tests your thinking skills." },
  // { word: "pedestal", hint: "A base that supports a statue or structure." },
  // { word: "anchor", hint: "Dropped from a boat to keep it in place." },
  // { word: "canopy", hint: "A covering, often formed by tree tops or fabric." },
  // { word: "cobweb", hint: "A spider's home, often seen in corners." },
  // { word: "pasture", hint: "Land covered with grass for grazing animals." },
  // { word: "tunnel", hint: "A passageway through or under something, like a mountain." },
  // { word: "goblet", hint: "A drinking glass with a stem and base." },
  // { word: "crater", hint: "A large hole, often caused by an explosion or impact." },
  // { word: "alchemy", hint: "An ancient practice aiming to turn metals into gold." },
  // { word: "window", hint: "You look through this to see outside." },
  // { word: "tundra", hint: "A cold, treeless region with frozen ground." },
    { word: "shinchan",hint: "He’s the little rascal who can’t sit still, is always in trouble, and has a talent for embarrassing everyone—especially his parents!"},

];
